package com.sltc.soa;

import java.util.HashMap;

public class GetCurrencyData {

    private HashMap<String, String> countryCodes = new HashMap<String, String>();

    public GetCurrencyData() {
        countryCodes.put("AED", "United Arab Emirates Dirham");
                countryCodes.put("AFN", "Afghan Afghani");
                countryCodes.put("ALL", "Albanian Lek");
                countryCodes.put("AMD", "Armenian Dram");
                countryCodes.put("ANG", "Netherlands Antillean Guilder");
                countryCodes.put("AOA", "Angolan Kwanza");
                countryCodes.put("ARS", "Argentine Peso");
                countryCodes.put("AUD", "Australian Dollar");
                countryCodes.put("AWG", "Aruban Florin");
                countryCodes.put("AZN", "Azerbaijani Manat");
                countryCodes.put("BAM", "Bosnia-Herzegovina Convertible Mark");
                countryCodes.put("BBD", "Barbadian Dollar");
                countryCodes.put("BDT", "Bangladeshi Taka");
                countryCodes.put("BGN", "Bulgarian Lev");
                countryCodes.put("BHD", "Bahraini Dinar");
                countryCodes.put("BIF", "Burundian Franc");
                countryCodes.put("BMD", "Bermudan Dollar");
                countryCodes.put("BND", "Brunei Dollar");
                countryCodes.put("BOB", "Bolivian Boliviano");
                countryCodes.put("BRL", "Brazilian Real");
                countryCodes.put("BSD", "Bahamian Dollar");
                countryCodes.put("BTC", "Bitcoin");
                countryCodes.put("BTN", "Bhutanese Ngultrum");
                countryCodes.put("BWP", "Botswanan Pula");
                countryCodes.put("BYN", "Belarusian Ruble");
                countryCodes.put("BZD", "Belize Dollar");
                countryCodes.put("CAD", "Canadian Dollar");
                countryCodes.put("CDF", "Congolese Franc");
                countryCodes.put("CHF", "Swiss Franc");
                countryCodes.put("CLF", "Chilean Unit of Account (UF)");
                countryCodes.put("CLP", "Chilean Peso");
                countryCodes.put("CNH", "Chinese Yuan (Offshore)");
                countryCodes.put("CNY", "Chinese Yuan");
                countryCodes.put("COP", "Colombian Peso");
                countryCodes.put("CRC", "Costa Rican Colón");
                countryCodes.put("CUC", "Cuban Convertible Peso");
                countryCodes.put("CUP", "Cuban Peso");
                countryCodes.put("CVE", "Cape Verdean Escudo");
                countryCodes.put("CZK", "Czech Republic Koruna");
                countryCodes.put("DJF", "Djiboutian Franc");
                countryCodes.put("DKK", "Danish Krone");
                countryCodes.put("DOP", "Dominican Peso");
                countryCodes.put("DZD", "Algerian Dinar");
                countryCodes.put("EGP", "Egyptian Pound");
                countryCodes.put("ERN", "Eritrean Nakfa");
                countryCodes.put("ETB", "Ethiopian Birr");
                countryCodes.put("EUR", "Euro");
                countryCodes.put("FJD", "Fijian Dollar");
                countryCodes.put("FKP", "Falkland Islands Pound");
                countryCodes.put("GBP", "British Pound Sterling");
                countryCodes.put("GEL", "Georgian Lari");
                countryCodes.put("GGP", "Guernsey Pound");
                countryCodes.put("GHS", "Ghanaian Cedi");
                countryCodes.put("GIP", "Gibraltar Pound");
                countryCodes.put("GMD", "Gambian Dalasi");
                countryCodes.put("GNF", "Guinean Franc");
                countryCodes.put("GTQ", "Guatemalan Quetzal");
                countryCodes.put("GYD", "Guyanaese Dollar");
                countryCodes.put("HKD", "Hong Kong Dollar");
                countryCodes.put("HNL", "Honduran Lempira");
                countryCodes.put("HRK", "Croatian Kuna");
                countryCodes.put("HTG", "Haitian Gourde");
                countryCodes.put("HUF", "Hungarian Forint");
                countryCodes.put("IDR", "Indonesian Rupiah");
                countryCodes.put("ILS", "Israeli New Sheqel");
                countryCodes.put("IMP", "Manx pound");
                countryCodes.put("INR", "Indian Rupee");
                countryCodes.put("IQD", "Iraqi Dinar");
                countryCodes.put("IRR", "Iranian Rial");
                countryCodes.put("ISK", "Icelandic Króna");
                countryCodes.put("JEP", "Jersey Pound");
                countryCodes.put("JMD", "Jamaican Dollar");
                countryCodes.put("JOD", "Jordanian Dinar");
                countryCodes.put("JPY", "Japanese Yen");
                countryCodes.put("KES", "Kenyan Shilling");
                countryCodes.put("KGS", "Kyrgystani Som");
                countryCodes.put("KHR", "Cambodian Riel");
                countryCodes.put("KMF", "Comorian Franc");
                countryCodes.put("KPW", "North Korean Won");
                countryCodes.put("KRW", "South Korean Won");
                countryCodes.put("KWD", "Kuwaiti Dinar");
                countryCodes.put("KYD", "Cayman Islands Dollar");
                countryCodes.put("KZT", "Kazakhstani Tenge");
                countryCodes.put("LAK", "Laotian Kip");
                countryCodes.put("LBP", "Lebanese Pound");
                countryCodes.put("LKR", "Sri Lankan Rupee");
                countryCodes.put("LRD", "Liberian Dollar");
                countryCodes.put("LSL", "Lesotho Loti");
                countryCodes.put("LYD", "Libyan Dinar");
                countryCodes.put("MAD", "Moroccan Dirham");
                countryCodes.put("MDL", "Moldovan Leu");
                countryCodes.put("MGA", "Malagasy Ariary");
                countryCodes.put("MKD", "Macedonian Denar");
                countryCodes.put("MMK", "Myanma Kyat");
                countryCodes.put("MNT", "Mongolian Tugrik");
                countryCodes.put("MOP", "Macanese Pataca");
                countryCodes.put("MRU", "Mauritanian Ouguiya");
                countryCodes.put("MUR", "Mauritian Rupee");
                countryCodes.put("MVR", "Maldivian Rufiyaa");
                countryCodes.put("MWK", "Malawian Kwacha");
                countryCodes.put("MXN", "Mexican Peso");
                countryCodes.put("MYR", "Malaysian Ringgit");
                countryCodes.put("MZN", "Mozambican Metical");
                countryCodes.put("NAD", "Namibian Dollar");
                countryCodes.put("NGN", "Nigerian Naira");
                countryCodes.put("NIO", "Nicaraguan Córdoba");
                countryCodes.put("NOK", "Norwegian Krone");
                countryCodes.put("NPR", "Nepalese Rupee");
                countryCodes.put("NZD", "New Zealand Dollar");
                countryCodes.put("OMR", "Omani Rial");
                countryCodes.put("PAB", "Panamanian Balboa");
                countryCodes.put("PEN", "Peruvian Nuevo Sol");
                countryCodes.put("PGK", "Papua New Guinean Kina");
                countryCodes.put("PHP", "Philippine Peso");
                countryCodes.put("PKR", "Pakistani Rupee");
                countryCodes.put("PLN", "Polish Zloty");
                countryCodes.put("PYG", "Paraguayan Guarani");
                countryCodes.put("QAR", "Qatari Rial");
                countryCodes.put("RON", "Romanian Leu");
                countryCodes.put("RSD", "Serbian Dinar");
                countryCodes.put("RUB", "Russian Ruble");
                countryCodes.put("RWF", "Rwandan Franc");
                countryCodes.put("SAR", "Saudi Riyal");
                countryCodes.put("SBD", "Solomon Islands Dollar");
                countryCodes.put("SCR", "Seychellois Rupee");
                countryCodes.put("SDG", "Sudanese Pound");
                countryCodes.put("SEK", "Swedish Krona");
                countryCodes.put("SGD", "Singapore Dollar");
                countryCodes.put("SHP", "Saint Helena Pound");
                countryCodes.put("SLL", "Sierra Leonean Leone");
                countryCodes.put("SOS", "Somali Shilling");
                countryCodes.put("SRD", "Surinamese Dollar");
                countryCodes.put("SSP", "South Sudanese Pound");
                countryCodes.put("STD", "São Tomé and Príncipe Dobra (pre-2018)");
                countryCodes.put("STN", "São Tomé and Príncipe Dobra");
                countryCodes.put("SVC", "Salvadoran Colón");
                countryCodes.put("SYP", "Syrian Pound");
                countryCodes.put("SZL", "Swazi Lilangeni");
                countryCodes.put("THB", "Thai Baht");
                countryCodes.put("TJS", "Tajikistani Somoni");
                countryCodes.put("TMT", "Turkmenistani Manat");
                countryCodes.put("TND", "Tunisian Dinar");
                countryCodes.put("TOP", "Tongan Pa'anga");
                countryCodes.put("TRY", "Turkish Lira");
                countryCodes.put("TTD", "Trinidad and Tobago Dollar");
                countryCodes.put("TWD", "New Taiwan Dollar");
                countryCodes.put("TZS", "Tanzanian Shilling");
                countryCodes.put("UAH", "Ukrainian Hryvnia");
                countryCodes.put("UGX", "Ugandan Shilling");
                countryCodes.put("USD", "United States Dollar");
                countryCodes.put("UYU", "Uruguayan Peso");
                countryCodes.put("UZS", "Uzbekistan Som");
                countryCodes.put("VEF", "Venezuelan Bolívar Fuerte (Old)");
                countryCodes.put("VES", "Venezuelan Bolívar Soberano");
                countryCodes.put("VND", "Vietnamese Dong");
                countryCodes.put("VUV", "Vanuatu Vatu");
                countryCodes.put("WST", "Samoan Tala");
                countryCodes.put("XAF", "CFA Franc BEAC");
                countryCodes.put("XAG", "Silver Ounce");
                countryCodes.put("XAU", "Gold Ounce");
                countryCodes.put("XCD", "East Caribbean Dollar");
                countryCodes.put("XDR", "Special Drawing Rights");
                countryCodes.put("XOF", "CFA Franc BCEAO");
                countryCodes.put("XPD", "Palladium Ounce");
                countryCodes.put("XPF", "CFP Franc");
                countryCodes.put("XPT", "Platinum Ounce");
                countryCodes.put("YER", "Yemeni Rial");
                countryCodes.put("ZAR", "South African Rand");
                countryCodes.put("ZMW", "Zambian Kwacha");
                countryCodes.put("ZWL", "Zimbabwean Dollar");
    }

    public HashMap<String, String> getCountryCodes() {
        return countryCodes;
    }

    public String getKey(String value) {
            String mapKey = null;
            for(String key : countryCodes.keySet()) {
                    if(value.equals(countryCodes.get(key))) {
                            mapKey = key;
                            break;
                    }
            }
            return mapKey;
    }
}
