
package com.sltc.soa.client.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoWS", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.ConvertResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/convertRequest", output = "http://soa.sltc.com/DemoWS/convertResponse")
    public double convert(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountryNames", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetCountryNames")
    @ResponseWrapper(localName = "getCountryNamesResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetCountryNamesResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/getCountryNamesRequest", output = "http://soa.sltc.com/DemoWS/getCountryNamesResponse")
    public List<String> getCountryNames();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountryCodes", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetCountryCodes")
    @ResponseWrapper(localName = "getCountryCodesResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetCountryCodesResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/getCountryCodesRequest", output = "http://soa.sltc.com/DemoWS/getCountryCodesResponse")
    public List<String> getCountryCodes();

}
